[package]
name = "spireai"
version = "0.1.0"
authors = ["Nathan Merrill <nathan.t.merrill@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.117"
serde_json = "1.0.59"
