[package]
name = "spireai"
version = "0.1.0"
authors = ["Nathan Merrill <nathan.t.merrill@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.117", features = ["derive"]}
serde_json = "1.0.59"
log = "0.4.14"
log4rs = "1.0.0"